export const actionTypes = {
    FETCH_STRUCTURE_COMPLETED: 'FETCH_STRUCTURE_COMPLETED',
    FETCH_DATA_LINK_COMPLETED: 'FETCH_DATA_LINK_COMPLETED',
    CHANGE_VALUE_TO_CHANNEL: 'CHANGE_VALUE_TO_CHANNEL'
};
